### ISSUE TITLE
Remove 'copy' hover button from snippets where irrelevant

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-microprofile-intro#21]
Apply `role=“no_copy”` to code snippets that are not intended to be copied (eg because they're just repeating sub-snippets and the user shouldn't copy/paste them).

**Comment by yeekangc** [comment]
@JunyiSun, can you please review the guide again to see if we missed something?

**Comment by evelinec** [comment]
I identified all the areas impacted. It comes down to three types of problems:
1. Some snippets do not need the copy mechanism (as Laura mentioned, they are the repeated snippets and do not need to be copied and pasted). 
2. Some snippets need to be partially copied and pasted.
3. Others are commands may or may not need to be copied and pasted. 
We will fix the first problem. Laura, are you also seeing the problems described in 2 and 3? Do you have any suggestions as of how to handle those? 

Thanks.

**Comment by lauracowen** [comment]
Just had a look and I think this is a bit more complicated and might need some additional updates to text for clarity. I'm going to raise a similar issue on the REST intro guide and I'll specify exactly which snippets should have copy buttons etc. That way, I'll have to think through each one and check if there are wording problems there too. The reason I'm picking the REST intro guide is that it was more thoroughly reviewed for usability. If we can get it right in the REST guide, we can then transfer the same solutions to the other guides, including the MicroProfile guide.

So don't close this issue but I think we should fix the REST guide first. Then come back to this one.

**Comment by lauracowen** [comment]
See: https://github.com/OpenLiberty/guide-rest-intro/issues/10

**Comment by JunyiSun** [comment]
Hi, I've looked through the guide again and removed unnecessary icons for copying. Look forward to more feedback!
