### ISSUE TITLE
Context Root Not Found in the start demo

### ISSUE THREAD

**Issue by litan1106** [OpenLiberty/guide-microprofile-intro#32]
I got "Context Root Not Found" in the start demo

http://localhost:9080/inventory/hosts

**Comment by JunyiSun** [comment]
Hi @litan1106 , would you mind elaborating your description a bit? It seems that you are trying to access the app before running it. 

The url `http://localhost:9080/inventory/hosts` is only available after you build and start the application by running `mvn install` and `mvn liberty:start-server`.

**Comment by litan1106** [comment]
Thank. I was in the start folder. The url should be http://localhost:9080/system/properties
