### ISSUE TITLE
Tighten focus and structure of MicroProfile guide

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-microprofile-intro#37]
@gcharters and I need to finish re-reviewing this guide to work out how to tighten its focus and structure, which should hopefully shorten it and simplify the structure of headings listed on the left, and also remove duplication with other guides (eg Maven guide).

I've intentionally assigned this to myself but I won't get to it straight away.

**Comment by yeekangc** [comment]
This probably relates to all the other issues we have currently opened -- #21, #22, #35 -- particularly #35.

We have PRs for them in #34 and #24 especially #34 for addressing some issues that we have found recently.

We should hold off on the above until we have the feedback from @lauracowen and @gcharters.  Then, we can do a comprehensive rework of the guide.  @evelinec @Kubik42 @sishida @JunyiSun, please take note.

**Comment by evelinec** [comment]
@lauracowen can you review this issue for closure? Thank you. 

Note, this guide had been archived.
