### ISSUE TITLE
Add a new header field for related guides

### ISSUE THREAD

**Issue by Kubik42** [OpenLiberty/guide-microprofile-intro#38]
There is a new header field `page-related-guides` which can be used for referencing similar guides to the current one. We should this to the existing guides.

Ex of commit: https://github.com/OpenLiberty/guide-rest-intro/commit/78b23fd023e824aa845bc218de91ab4abcc6c640
Ex on dev site (on the side and near the bottom): https://openlibertydev.mybluemix.net/guides/rest-intro.html

**Comment by evelinec** [comment]
I think this is not needed anymore for this guide. @yeekangc can you confirm? Thanks.

**Comment by yeekangc** [comment]
After the MP intro guide is taken out from the list and redirected to the new CDI intro guide, yes.
