### ISSUE TITLE
Need to pre-populate directory structures

### ISSUE THREAD

**Issue by kwsutter** [OpenLiberty/guide-microprofile-intro#39]
I just did the static "Creating a MicroProfile Application" guide in prep for creating a VM image for a Think conference lab.  Everything worked out quite well, but I have a couple of observations...

In the [Testing Section](https://openliberty.io/guides/microprofile-intro.html#testing-the-microprofile-application), we need to highlight that we're dealing with a totally separate directory structure.

First off, I would pre-create the src/test/java/it/io/openliberty/guides/microprofile/ directory structure in the "start" directory.  You had pre-created the development (src/main/java/io/openliberty/guides/microprofile/), so do the same for the "it" test directory.

(BTW, that comment should apply to all of the guides.  Not just this MicroProfile guide.  I just haven't had the chance to test out all the rest yet...)

And, then within this Testing Section, you need to highlight the fact that we are now working in the totally separate "it" directory structure.  If you read this too quickly (which I did), you will notice the tiny "it" and assume you are still talking about the development directory structure.  And, you get some pretty strange build errors if you put the testing files in the development structure.  The maven dependencies don't work right.  And, then you try to correct them, and then you get strange compile errors...  It's just a mess.

Hope this was clear.  Thanks!

**Comment by evelinec** [comment]
Also verified that we have documented this in our "Getting Started" guide.

**Comment by kwsutter** [comment]
This issue is still Open.  The comments indicate that work was done.  Are there PRs or Commits or some other Issues to reference so that we could close this out?  Thanks.

**Comment by JunyiSun** [comment]
@kwsutter Please check #42 to see if it address you concerns. It pre-creates the required test directory in the start/.
