### ISSUE TITLE
Build with tests is failing because Java 9+ has deprecated some javax.* packages 

### ISSUE THREAD

**Issue by gorlok** [OpenLiberty/guide-microprofile-intro#48]
You need to activate that modules (but they will be removed later), or you need to add these new dependencies at least (I prefer this):

```
<dependency>
  <groupId>javax.xml.bind</groupId>
  <artifactId>jaxb-api</artifactId>
  <version>2.3.0</version>
</dependency>

<dependency>
    <groupId>javax.activation</groupId>
    <artifactId>activation</artifactId>
    <version>1.1.1</version>
</dependency>
```
'mvn clean install' is failing if you don't skip test.

**Comment by yeekangc** [comment]
Thank you for the feedback, @gorlok.  We will look into it.

FYI, the next long-term Java release that we intend to support is Java 11.  Details can be found in https://github.com/OpenLiberty/open-liberty/issues/540.

**Comment by evelinec** [comment]
@proubatsis can you confirm the fix and tests are good for this guide?

**Comment by evelinec** [comment]
@gorlok Thank you for raising the issue. It's resolved and tested.
